In [24]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv("../datasets/customer_ml_datasets.csv")

In [28]:
df.head()

,customer_id,total_sessions,total_orders,total_spend,average_order_value,cart_abandonment_rate,average_discount_used,customer_satisfaction,preferred_device,city,preferred_category,total_products_purchased,total_pages_viewed,average_time_on_site,total_review_votes,preferred_payment_method,rn,churn
0,1000,2,1,1228.72,1228.72,0.50,17.50,3.50,1,204,7,7,35,1014.00,44,4,1,0
1,1001,1,0,0.00,NaN,0.00,0.00,4.00,0,101,3,4,15,996.00,0,4,2,0
2,1002,3,0,0.00,NaN,0.67,3.33,4.00,1,90,6,8,25,313.67,0,5,3,0
3,1003,3,1,1681.96,1681.96,0.00,11.67,4.33,1,87,4,9,17,695.33,4,2,4,0
4,1004,3,0,0.00,NaN,0.33,16.67,4.00,1,97,5,5,37,923.67,0,5,5,0

In [29]:
df.shape

(1000, 18)

In [30]:
df.columns.tolist()

['customer_id',
 'total_sessions',
 'total_orders',
 'total_spend',
 'average_order_value',
 'cart_abandonment_rate',
 'average_discount_used',
 'customer_satisfaction',
 'preferred_device',
 'city',
 'preferred_category',
 'total_products_purchased',
 'total_pages_viewed',
 'average_time_on_site',
 'total_review_votes',
 'preferred_payment_method',
 'rn',
 'churn']

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               1000 non-null   int64
 1   total_sessions            1000 non-null   int64
 2   total_orders              1000 non-null   int64
 3   total_spend               1000 non-null   float64
 4   average_order_value       491 non-null    float64
 5   cart_abandonment_rate     1000 non-null   float64
 6   average_discount_used     1000 non-null   float64
 7   customer_satisfaction     1000 non-null   float64
 8   preferred_device          1000 non-null   int64
 9   city                      1000 non-null   int64
 10  preferred_category        1000 non-null   int64
 11  total_products_purchased  1000 non-null   int64
 12  total_pages_viewed        1000 non-null   int64
 13  average_time_on_site      1000 non-null   float64
 14  total_review_votes        1000 non-null   int64
 15  preferred_payment_method  1000 non-null   int64
 16  rn                        1000 non-null   int64
 17  churn                     1000 non-null   int64
dtypes: float64(6), int64(12)
memory usage: 140.8 KB

In [34]:
df.isnull().sum().sort_values(
    ascending=False
)

average_order_value         509
customer_id                   0
preferred_category            0
rn                            0
preferred_payment_method      0
total_review_votes            0
average_time_on_site          0
total_pages_viewed            0
total_products_purchased      0
city                          0
total_sessions                0
preferred_device              0
customer_satisfaction         0
average_discount_used         0
cart_abandonment_rate         0
total_spend                   0
total_orders                  0
churn                         0
dtype: int64

In [35]:
missing_percentage = (
    df.isnull().sum() /
    len(df)
) * 100

missing_percentage.sort_values(
    ascending=False
)

average_order_value         50.9
customer_id                  0.0
preferred_category           0.0
rn                           0.0
preferred_payment_method     0.0
total_review_votes           0.0
average_time_on_site         0.0
total_pages_viewed           0.0
total_products_purchased     0.0
city                         0.0
total_sessions               0.0
preferred_device             0.0
customer_satisfaction        0.0
average_discount_used        0.0
cart_abandonment_rate        0.0
total_spend                  0.0
total_orders                 0.0
churn                        0.0
dtype: float64

In [36]:
df.duplicated().sum()

0

In [37]:
df.drop_duplicates(
    inplace=True
)

In [13]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

In [38]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
)

In [39]:
df.replace(
    ['', ' ', 'NA', 'N/A', 'null', 'NULL'],
    np.nan,
    inplace=True
)

In [42]:
numeric_columns = [
    'total_sessions',
    'total_orders',
    'total_spend',
    'average_order_value',
    'cart_abandonment_rate',
    'average_discount_used',
    'customer_satisfaction',
    'preferred_device',
    'city',
    'preferred_category',
    'total_products_purchased',
    'total_pages_viewed',
    'average_time_on_site',
    'total_review_votes',
    'preferred_payment_method',
    'rn',
    'churn'
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors='coerce'
    )

In [43]:
df.isnull().sum()

customer_id                   0
total_sessions                0
total_orders                  0
total_spend                   0
average_order_value         509
cart_abandonment_rate         0
average_discount_used         0
customer_satisfaction         0
preferred_device              0
city                          0
preferred_category            0
total_products_purchased      0
total_pages_viewed            0
average_time_on_site          0
total_review_votes            0
preferred_payment_method      0
rn                            0
churn                         0
dtype: int64

In [44]:
for column in numeric_columns:
    df[column].fillna(
        df[column].median(),
        inplace=True
    )

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               1000 non-null   int64
 1   total_sessions            1000 non-null   int64
 2   total_orders              1000 non-null   int64
 3   total_spend               1000 non-null   float64
 4   average_order_value       1000 non-null   float64
 5   cart_abandonment_rate     1000 non-null   float64
 6   average_discount_used     1000 non-null   float64
 7   customer_satisfaction     1000 non-null   float64
 8   preferred_device          1000 non-null   int64
 9   city                      1000 non-null   int64
 10  preferred_category        1000 non-null   int64
 11  total_products_purchased  1000 non-null   int64
 12  total_pages_viewed        1000 non-null   int64
 13  average_time_on_site      1000 non-null   float64
 14  total_review_votes        1000 non-null   int64
 15  preferred_payment_method  1000 non-null   int64
 16  rn                        1000 non-null   int64
 17  churn                     1000 non-null   int64
dtypes: float64(6), int64(12)
memory usage: 140.8 KB

In [46]:
df.describe()

,customer_id,total_sessions,total_orders,total_spend,average_order_value,cart_abandonment_rate,average_discount_used,customer_satisfaction,preferred_device,city,preferred_category,total_products_purchased,total_pages_viewed,average_time_on_site,total_review_votes,preferred_payment_method,rn,churn
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1524.031000,2.915000,0.670000,1199.307420,1606.805560,0.411710,9.057800,3.956580,1.14200,94.349000,5.119000,7.342000,36.759000,911.943910,16.589000,3.659000,500.500000,0.109000
std,303.457926,1.487275,0.820837,1905.880101,998.652549,0.327058,6.224389,0.342832,0.60349,62.835241,1.854259,4.221001,22.379181,348.861867,22.903114,1.459743,288.819436,0.311795
min,1000.000000,1.000000,0.000000,0.000000,90.970000,0.000000,0.000000,2.000000,0.00000,2.000000,0.000000,1.000000,1.000000,34.000000,0.000000,0.000000,1.000000,0.000000
25%,1261.750000,2.000000,0.000000,0.000000,1399.000000,0.000000,5.000000,4.000000,1.00000,48.000000,4.000000,4.000000,20.750000,691.750000,0.000000,3.000000,250.750000,0.000000
50%,1524.500000,3.000000,0.000000,0.000000,1399.000000,0.400000,8.750000,4.000000,1.00000,80.000000,6.000000,7.000000,34.000000,925.450000,0.000000,4.000000,500.500000,0.000000
75%,1785.250000,4.000000,1.000000,1824.170000,1399.000000,0.600000,12.500000,4.000000,2.00000,136.000000,7.000000,10.000000,50.000000,1122.082500,31.000000,5.000000,750.250000,0.000000
max,2048.000000,8.000000,5.000000,13800.960000,7889.360000,1.000000,30.000000,5.000000,2.00000,224.000000,7.000000,24.000000,134.000000,1758.000000,126.000000,5.000000,1000.000000,1.000000

In [47]:
df['churn'].value_counts()

churn
0    891
1    109
Name: count, dtype: int64

In [48]:
df['churn'].value_counts(normalize=True) * 100

churn
0    89.1
1    10.9
Name: proportion, dtype: float64

In [49]:
df.to_csv(
    "../datasets/customer_ml_dataset_cleaned.csv",
    index=False
)